name: m4dvap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - laspy[lazrs]
  - rasterio
  - matplotlib
  - plyfile
  - shapely
  - fiona
  - pip
  - pip:
    - opencv-python
    - py4dgeo
    - git+https://github.com/3dgeo-heidelberg/vapc.git@main